# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 10:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170628_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='question_content',
            field=models.TextField(default=django.utils.timezone.now, max_length=5000, verbose_name='content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='number of votes'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='number of votes'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Tag must be alphanumerics separated by a dash', regex='^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$')], verbose_name='tag'),
        ),
    ]
