# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reputation',
            field=models.CharField(choices=[('amateur', 'Amateur'), ('seasoned', 'Seasoned'), ('topuser', 'Top User'), ('guru', 'Guru')], default='amateur', max_length=7),
        ),
    ]
