# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170628_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, to='profiles.Profile'),
        ),
    ]
